spring:
  jpa:
    database: postgresql
    hibernate.ddl-auto: update
  datasource:
    driver-class-processDefinitionName: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://postgresql:5432/orchestrator
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 10

  data:
    cassandra:
      contact-points: AC-node1,AC-node2,AC-node3
      keyspace-name: ocds
      port: 9042
      username: caclient
      password: brT4Kn27RQs

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://eureka-peer-1:8800/eureka/,http://eureka-peer-2:8800/eureka/

kafka:
  producer:
    bootstrap: AK-node1:9092,AK-node2:9092,AK-node3:9092
    topic: chronograph_in
  consumer:
    bootstrap: AK-node1:9092,AK-node2:9092,AK-node3:9092
    group: orchestrator
    topic: chronograph_out

camunda:
  bpm:
    auto-deployment-enabled: true
    history-level: none

#e-access:
#  ribbon:
#    eureka:
#      enabled: true
#e-notice:
#  ribbon:
#    eureka:
#      enabled: true

ocds:
  prefix: ocds-t1s2t3
