server:
  port: 8088

logging.level: error

spring:
  jpa:
    database: mysql
    hibernate.ddl-auto: update
  datasource:
    driver-class-processDefinitionName: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/orchestrator?useSSL=false
    username: root
    password: mysql
    hikari:
      maximum-pool-size: 10

#  data:
#    cassandra:
#      contact-points: 127.0.0.1
#      keyspace-name: ocds
#      port: 9042
#      username: cassandra
#      password: cassandra

#kafka:
#  producer:
#    bootstrap: localhost:9092
#    topic: orchestrator
#  consumer:
#    bootstrap: localhost:9092
#    group: orchestrator
#    topic: chronograph


#camunda:
#  bpm:
#    application:
#      isDeleteUponUndeploy: false
#      isScanForProcessDefinitions: true
#      isDeployChangedOnly: true
#      isResumePreviousVersions: true
#      resumePreviousBy: a value
#    job-execution:
#      enabled: true
#    metrics:
#      enabled: false
#      db-reporter-activate: false

ocds.prefix: ocds-t1s2t3

camunda:
  bpm:
    auto-deployment-enabled: true
