server:
  port: 8080

spring:
  profiles:
    active: local
  application:
    name: bpe
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://10.0.20.112:5432/orchestrator
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 10
      pool-name: orchestrator-pool

cassandra:
  contact-points: 10.0.20.104,10.0.20.105,10.0.20.106
  keyspace-name: ocds
  username: caclient
  password: 6AH7vbrkMWnfK

uri:
  budget: http://dev.public.eprocurement.systems/budget/
  tender: http://dev.public.eprocurement.systems/tender/

camunda:
  bpm:
    auto-deployment-enabled: true
    history-level: none

feign:
  hystrix:
    enabled: false
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 10000

ribbon:
  eureka:
    enabled: false
e-budget:
  ribbon:
    listOfServers: http://10.0.20.125:9051
e-access:
  ribbon:
    listOfServers: http://10.0.20.125:9031
e-notice:
  ribbon:
    listOfServers: http://10.0.20.125:9041
e-submission:
  ribbon:
    listOfServers: http://10.0.20.125:9061
e-clarification:
  ribbon:
    listOfServers: http://10.0.20.125:9071
e-storage:
  ribbon:
    listOfServers: http://10.0.20.125:9131
e-qualification:
  ribbon:
    listOfServers: http://10.0.20.125:9091
e-evaluation:
  ribbon:
    listOfServers: http://10.0.20.125:9081
e-contracting:
  ribbon:
    listOfServers: http://10.0.20.125:9151
e-mdm:
  ribbon:
    listOfServers: http://10.0.20.125:9161

logging:
  ##  level:
  ##    root: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"