server:
  port: 9090

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://10.0.10.112:5432/orchestrator
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 10
      pool-name: orchestrator-pool

cassandra:
  contact-points: ac-node1.eprocurement.systems,ac-node2.eprocurement.systems,ac-node3.eprocurement.systems
  keyspace-name: ocds
  username: caclient
  password: brT4Kn27RQs

kafka:
  producer:
    bootstrap: ak-node1.eprocurement.systems:9092,ak-node2.eprocurement.systems:9092,ak-node3.eprocurement.systems:9092
    topic: orchestrator
  consumer:
    bootstrap: localhost:9092
    group: orchestrator
    topic: chronograph

ocds.prefix: ocds-t1s2t3

camunda:
  bpm:
    auto-deployment-enabled: true
    history-level: none

ribbon:
   eureka:
    enabled: false
e-access:
  ribbon:
    listOfServers: http://localhost:9031
e-notice:
  ribbon:
    listOfServers: http://localhost:9041
e-submission:
  ribbon:
    listOfServers: http://localhost:9051
e-clarification:
  ribbon:
    listOfServers: http://localhost:9061
e-storage:
  ribbon:
    listOfServers: http://localhost:9071

logging:
  level: error