server:
  port: 8080

spring:
  profiles:
    active: local
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/orchestrator
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 10
      pool-name: orchestrator-pool

cassandra:
  contact-points: localhost
  keyspace-name: ocds
  port: 9042

uri:
  budget: http://dev.public.eprocurement.systems/budget/
  tender: http://dev.public.eprocurement.systems/tender/

camunda:
  bpm:
    auto-deployment-enabled: true
    history-level: none
    admin-user:
      id: demo
      password: demo123

feign:
  hystrix:
    enabled: false
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 10000

notification:
  incident:
    bootstrap-servers: localhost:9092
    retries: 5
    topic: incidents

  platform:
    bootstrap-servers: localhost:9092
    retries: 5
    topic: notification-kafka-channel

components:
  eAccess:
    host: e-access
    port: 9031
  eRevision:
    host: e-revision
    port: 9351
  storage:
    host: storage
    port: 9131
  eNotice:
    host: e-notice
    port: 9041
  eDossier:
    host: e-dossier
    port: 9251
  eEvaluation:
    host: e-evaluation
    port: 9081
  eContracting:
    host: e-contracting
    port: 9151
  eQualification:
    host: e-qualification
    port: 9091
  eClarification:
    host: e-clarification
    port: 9071
  mdm:
    host: mdm
    port: 9161
  eSubmission:
    host: e-submission
    port: 9061
  eAuction:
    host: 10.0.20.125
    port: 9191

ribbon:
  eureka:
    enabled: false
e-budget:
  ribbon:
    listOfServers: http://10.0.20.125:9051
e-access:
  ribbon:
    listOfServers: http://10.0.20.125:9031
e-auction:
  ribbon:
    listOfServers: http://10.0.20.125:9191
e-notice:
  ribbon:
    listOfServers: http://10.0.20.125:9041
e-submission:
  ribbon:
    listOfServers: http://10.0.20.125:9061
e-clarification:
  ribbon:
    listOfServers: http://10.0.20.125:9071
e-storage:
  ribbon:
    listOfServers: http://10.0.20.125:9131
e-qualification:
  ribbon:
    listOfServers: http://10.0.20.125:9091
e-evaluation:
  ribbon:
    listOfServers: http://10.0.20.125:9081
e-contracting:
  ribbon:
    listOfServers: http://10.0.20.125:9151
e-regulation:
  ribbon:
    listOfServers: http://10.0.20.125:9201
e-mdm:
  ribbon:
    listOfServers: http://10.0.20.125:9161
e-dossier:
  ribbon:
    listOfServers: http://10.0.20.125:9042

logging:
  ##  level:
  ##    root: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"