server:
  port: 8900

logging.level: error

spring:
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/orchestrator
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 10
      pool-name: orchestrator-pool

cassandra:
  datasource:
    contact-point: 127.0.0.1
    keyspace: ocds
    username: cassandra
    password: cassandra

#kafka:
#  producer:
#    bootstrap: localhost:9092
#    topic: orchestrator
#  consumer:
#    bootstrap: localhost:9092
#    group: orchestrator
#    topic: chronograph

ocds.prefix: ocds-t1s2t3

camunda:
  bpm:
    auto-deployment-enabled: true
    history-level: none

e-submission:
  ribbon:
    eureka:
      enabled: false
    listOfServers: http://localhost:8080
e-access:
  ribbon:
    eureka:
      enabled: false
    listOfServers: http://localhost:8081
e-notice:
  ribbon:
    eureka:
      enabled: false
    listOfServers: http://localhost:8082
