server:
  port: 8080

spring:
  application:
    name: orchestrator
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/orchestrator
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 10
      pool-name: orchestrator-pool

kafka:
  producer:
    internal-bootstrap: AK-node1.eprocurement.systems:9092,AK-node2.eprocurement.systems:9092,AK-node3.eprocurement.systems:9092
    external-bootstrap: feed.eprocurement.systems:9092
  consumer:
    internal-bootstrap: AK-node1.eprocurement.systems:9092,AK-node2.eprocurement.systems:9092,AK-node3.eprocurement.systems:9092
    group: orchestrator

cassandra:
  contact-points: ac-node1.eprocurement.systems,ac-node2.eprocurement.systems,ac-node3.eprocurement.systems
  keyspace-name: ocds
  username: caclient
  password: brT4Kn27RQs

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://10.0.10.116:8801/eureka/,http://10.0.10.116:8802/eureka/

ocds.prefix: ocds-t1s2t3

camunda:
  bpm:
    auto-deployment-enabled: true
    history-level: none

ribbon:
   eureka:
    enabled: false
e-budget:
  ribbon:
    listOfServers: http://10.0.10.116:9051
e-access:
  ribbon:
    listOfServers: http://10.0.10.116:9031
e-notice:
  ribbon:
    listOfServers: http://10.0.10.116:9041
e-submission:
  ribbon:
    listOfServers: http://10.0.10.116:9061
e-clarification:
  ribbon:
    listOfServers: http://10.0.10.116:9071
e-storage:
  ribbon:
    listOfServers: http://10.0.10.116:9131

#logging:
#  level:
#    root: ERROR